package POO;

public class Introduccion {
    
}

/*          *** PROGRAMACION ORIENTADA A OBJETOS ***

- LENGUAJE MODERNO ORIENTADOS A OBJETOS
- COMPORTAMIENTO SIMILAR A LOS OBJETOS DE LA VIDA REAL
- ESTADO / PROPIEDADES / COMPORTAMIENTOS
- MODULARIZACION EN CLASES (DIFERENTES COMPONENTES QUE FORMAN UN TODO)

                
                ** VOCABULARIO POO EN JAVA **

   PAQUETES: MEJOR ORGANIZACION DE CLASES EN CARPETAS


1- CLASE: - MODELO DONDE SE REDACTAN LAS CARACTERISTICAS COMUNES DE UN GRUPO DE OBJETOS
           - CARACTERISTICAS COMUNES A UN OBJETO 
              -LUEGO LOS OBJETOS PERTENECEN A ESA CLASE

2- OBJETO: - TIENEN PROPIEDADES == ATRIBUTOS (QUE LOS DEFINEN)
            - TENEN COMPORTAMIENTOS == METODOS (QUE PUEDEN HACER)

ESTRUCTURA ATRIBUTO ----> nombre.propiedad = valor

renault.color = "rojo";
renault.peso = 1500;
renault.ancho = 2000;

ESTRUCTURA METODO ----> nombre.metodo ()

renault.arranca();
renault.gira();
renault.acelerea():


* METODO CONSTRUCTOR *
    
- Metodo especial que se encarga de dar un estado inicial a nuestro OBJETO
    
- Estructura: ---> public NOMBRE_IGUAL_A_LA_CLASE (){


3- ENCAPSULAMIENTO: LAS CLASES SE COMUNICAN ENTRE SI CON *** METODOS ***
        - PARA BLOQUEAR LA MODIFICACION DE LOS ATRIBUTOS SE DEBEN ENCAPSULAR
            -USO DE MODIFICADORES DE ACCESO public / private / protected
                -USO DE METODOS PARA ACCEDER A ATRIBUTOS GETTER / SETTER
*/