package POO;

public class Introduccion {
    
}

/*          *** PROGRAMACION ORIENTADA A OBJETOS ***

- LENGUAJE MODERNO ORIENTADOS A OBJETOS
- COMPORTAMIENTO SIMILAR A LOS OBJETOS DE LA VIDA REAL
- ESTADO / PROPIEDADES / COMPORTAMIENTOS
- MODULARIZACION EN CLASES (DIFERENTES COMPONENTES QUE FORMAN UN TODO)







*/